# EKS 1.33 Disable AMI Registry
# Entries are appended here after Jira approval
amis:
- name: rbrk-eks-1.33-test-disable
  jira: https://aitestsoc112233.atlassian.net/browse/KAN-64
- name: rbrk-eks-1.33-v2-disable
  jira: https://aitestsoc112233.atlassian.net/browse/KAN-67
- name: rbrk-eks-1.33-demo-3
  jira: https://aitestsoc112233.atlassian.net/browse/KAN-70
